// Code generated by counterfeiter. DO NOT EDIT.
package storagefakes

import (
	"sync"

	"github.com/NikolayDPaev/CentralisedVersionControl/netio"
	"github.com/NikolayDPaev/CentralisedVersionControl/server/servercommit"
	"github.com/NikolayDPaev/CentralisedVersionControl/server/storage"
)

type FakeStorage struct {
	BlobExistsStub        func(string) (bool, error)
	blobExistsMutex       sync.RWMutex
	blobExistsArgsForCall []struct {
		arg1 string
	}
	blobExistsReturns struct {
		result1 bool
		result2 error
	}
	blobExistsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	BlobSizeStub        func(string) (int64, error)
	blobSizeMutex       sync.RWMutex
	blobSizeArgsForCall []struct {
		arg1 string
	}
	blobSizeReturns struct {
		result1 int64
		result2 error
	}
	blobSizeReturnsOnCall map[int]struct {
		result1 int64
		result2 error
	}
	CommitExistsStub        func(string) (bool, error)
	commitExistsMutex       sync.RWMutex
	commitExistsArgsForCall []struct {
		arg1 string
	}
	commitExistsReturns struct {
		result1 bool
		result2 error
	}
	commitExistsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	CommitListStub        func() []string
	commitListMutex       sync.RWMutex
	commitListArgsForCall []struct {
	}
	commitListReturns struct {
		result1 []string
	}
	commitListReturnsOnCall map[int]struct {
		result1 []string
	}
	CommitSizeStub        func(string) (int64, error)
	commitSizeMutex       sync.RWMutex
	commitSizeArgsForCall []struct {
		arg1 string
	}
	commitSizeReturns struct {
		result1 int64
		result2 error
	}
	commitSizeReturnsOnCall map[int]struct {
		result1 int64
		result2 error
	}
	OpenBlobStub        func(string) (storage.StorageEntry, error)
	openBlobMutex       sync.RWMutex
	openBlobArgsForCall []struct {
		arg1 string
	}
	openBlobReturns struct {
		result1 storage.StorageEntry
		result2 error
	}
	openBlobReturnsOnCall map[int]struct {
		result1 storage.StorageEntry
		result2 error
	}
	OpenCommitStub        func(string) (*servercommit.Commit, error)
	openCommitMutex       sync.RWMutex
	openCommitArgsForCall []struct {
		arg1 string
	}
	openCommitReturns struct {
		result1 *servercommit.Commit
		result2 error
	}
	openCommitReturnsOnCall map[int]struct {
		result1 *servercommit.Commit
		result2 error
	}
	SaveBlobStub        func(string, netio.Communicator) error
	saveBlobMutex       sync.RWMutex
	saveBlobArgsForCall []struct {
		arg1 string
		arg2 netio.Communicator
	}
	saveBlobReturns struct {
		result1 error
	}
	saveBlobReturnsOnCall map[int]struct {
		result1 error
	}
	SaveCommitStub        func(*servercommit.Commit) error
	saveCommitMutex       sync.RWMutex
	saveCommitArgsForCall []struct {
		arg1 *servercommit.Commit
	}
	saveCommitReturns struct {
		result1 error
	}
	saveCommitReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStorage) BlobExists(arg1 string) (bool, error) {
	fake.blobExistsMutex.Lock()
	ret, specificReturn := fake.blobExistsReturnsOnCall[len(fake.blobExistsArgsForCall)]
	fake.blobExistsArgsForCall = append(fake.blobExistsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.BlobExistsStub
	fakeReturns := fake.blobExistsReturns
	fake.recordInvocation("BlobExists", []interface{}{arg1})
	fake.blobExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStorage) BlobExistsCallCount() int {
	fake.blobExistsMutex.RLock()
	defer fake.blobExistsMutex.RUnlock()
	return len(fake.blobExistsArgsForCall)
}

func (fake *FakeStorage) BlobExistsCalls(stub func(string) (bool, error)) {
	fake.blobExistsMutex.Lock()
	defer fake.blobExistsMutex.Unlock()
	fake.BlobExistsStub = stub
}

func (fake *FakeStorage) BlobExistsArgsForCall(i int) string {
	fake.blobExistsMutex.RLock()
	defer fake.blobExistsMutex.RUnlock()
	argsForCall := fake.blobExistsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStorage) BlobExistsReturns(result1 bool, result2 error) {
	fake.blobExistsMutex.Lock()
	defer fake.blobExistsMutex.Unlock()
	fake.BlobExistsStub = nil
	fake.blobExistsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeStorage) BlobExistsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.blobExistsMutex.Lock()
	defer fake.blobExistsMutex.Unlock()
	fake.BlobExistsStub = nil
	if fake.blobExistsReturnsOnCall == nil {
		fake.blobExistsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.blobExistsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeStorage) BlobSize(arg1 string) (int64, error) {
	fake.blobSizeMutex.Lock()
	ret, specificReturn := fake.blobSizeReturnsOnCall[len(fake.blobSizeArgsForCall)]
	fake.blobSizeArgsForCall = append(fake.blobSizeArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.BlobSizeStub
	fakeReturns := fake.blobSizeReturns
	fake.recordInvocation("BlobSize", []interface{}{arg1})
	fake.blobSizeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStorage) BlobSizeCallCount() int {
	fake.blobSizeMutex.RLock()
	defer fake.blobSizeMutex.RUnlock()
	return len(fake.blobSizeArgsForCall)
}

func (fake *FakeStorage) BlobSizeCalls(stub func(string) (int64, error)) {
	fake.blobSizeMutex.Lock()
	defer fake.blobSizeMutex.Unlock()
	fake.BlobSizeStub = stub
}

func (fake *FakeStorage) BlobSizeArgsForCall(i int) string {
	fake.blobSizeMutex.RLock()
	defer fake.blobSizeMutex.RUnlock()
	argsForCall := fake.blobSizeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStorage) BlobSizeReturns(result1 int64, result2 error) {
	fake.blobSizeMutex.Lock()
	defer fake.blobSizeMutex.Unlock()
	fake.BlobSizeStub = nil
	fake.blobSizeReturns = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *FakeStorage) BlobSizeReturnsOnCall(i int, result1 int64, result2 error) {
	fake.blobSizeMutex.Lock()
	defer fake.blobSizeMutex.Unlock()
	fake.BlobSizeStub = nil
	if fake.blobSizeReturnsOnCall == nil {
		fake.blobSizeReturnsOnCall = make(map[int]struct {
			result1 int64
			result2 error
		})
	}
	fake.blobSizeReturnsOnCall[i] = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *FakeStorage) CommitExists(arg1 string) (bool, error) {
	fake.commitExistsMutex.Lock()
	ret, specificReturn := fake.commitExistsReturnsOnCall[len(fake.commitExistsArgsForCall)]
	fake.commitExistsArgsForCall = append(fake.commitExistsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.CommitExistsStub
	fakeReturns := fake.commitExistsReturns
	fake.recordInvocation("CommitExists", []interface{}{arg1})
	fake.commitExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStorage) CommitExistsCallCount() int {
	fake.commitExistsMutex.RLock()
	defer fake.commitExistsMutex.RUnlock()
	return len(fake.commitExistsArgsForCall)
}

func (fake *FakeStorage) CommitExistsCalls(stub func(string) (bool, error)) {
	fake.commitExistsMutex.Lock()
	defer fake.commitExistsMutex.Unlock()
	fake.CommitExistsStub = stub
}

func (fake *FakeStorage) CommitExistsArgsForCall(i int) string {
	fake.commitExistsMutex.RLock()
	defer fake.commitExistsMutex.RUnlock()
	argsForCall := fake.commitExistsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStorage) CommitExistsReturns(result1 bool, result2 error) {
	fake.commitExistsMutex.Lock()
	defer fake.commitExistsMutex.Unlock()
	fake.CommitExistsStub = nil
	fake.commitExistsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeStorage) CommitExistsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.commitExistsMutex.Lock()
	defer fake.commitExistsMutex.Unlock()
	fake.CommitExistsStub = nil
	if fake.commitExistsReturnsOnCall == nil {
		fake.commitExistsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.commitExistsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeStorage) CommitList() []string {
	fake.commitListMutex.Lock()
	ret, specificReturn := fake.commitListReturnsOnCall[len(fake.commitListArgsForCall)]
	fake.commitListArgsForCall = append(fake.commitListArgsForCall, struct {
	}{})
	stub := fake.CommitListStub
	fakeReturns := fake.commitListReturns
	fake.recordInvocation("CommitList", []interface{}{})
	fake.commitListMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStorage) CommitListCallCount() int {
	fake.commitListMutex.RLock()
	defer fake.commitListMutex.RUnlock()
	return len(fake.commitListArgsForCall)
}

func (fake *FakeStorage) CommitListCalls(stub func() []string) {
	fake.commitListMutex.Lock()
	defer fake.commitListMutex.Unlock()
	fake.CommitListStub = stub
}

func (fake *FakeStorage) CommitListReturns(result1 []string) {
	fake.commitListMutex.Lock()
	defer fake.commitListMutex.Unlock()
	fake.CommitListStub = nil
	fake.commitListReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeStorage) CommitListReturnsOnCall(i int, result1 []string) {
	fake.commitListMutex.Lock()
	defer fake.commitListMutex.Unlock()
	fake.CommitListStub = nil
	if fake.commitListReturnsOnCall == nil {
		fake.commitListReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.commitListReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeStorage) CommitSize(arg1 string) (int64, error) {
	fake.commitSizeMutex.Lock()
	ret, specificReturn := fake.commitSizeReturnsOnCall[len(fake.commitSizeArgsForCall)]
	fake.commitSizeArgsForCall = append(fake.commitSizeArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.CommitSizeStub
	fakeReturns := fake.commitSizeReturns
	fake.recordInvocation("CommitSize", []interface{}{arg1})
	fake.commitSizeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStorage) CommitSizeCallCount() int {
	fake.commitSizeMutex.RLock()
	defer fake.commitSizeMutex.RUnlock()
	return len(fake.commitSizeArgsForCall)
}

func (fake *FakeStorage) CommitSizeCalls(stub func(string) (int64, error)) {
	fake.commitSizeMutex.Lock()
	defer fake.commitSizeMutex.Unlock()
	fake.CommitSizeStub = stub
}

func (fake *FakeStorage) CommitSizeArgsForCall(i int) string {
	fake.commitSizeMutex.RLock()
	defer fake.commitSizeMutex.RUnlock()
	argsForCall := fake.commitSizeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStorage) CommitSizeReturns(result1 int64, result2 error) {
	fake.commitSizeMutex.Lock()
	defer fake.commitSizeMutex.Unlock()
	fake.CommitSizeStub = nil
	fake.commitSizeReturns = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *FakeStorage) CommitSizeReturnsOnCall(i int, result1 int64, result2 error) {
	fake.commitSizeMutex.Lock()
	defer fake.commitSizeMutex.Unlock()
	fake.CommitSizeStub = nil
	if fake.commitSizeReturnsOnCall == nil {
		fake.commitSizeReturnsOnCall = make(map[int]struct {
			result1 int64
			result2 error
		})
	}
	fake.commitSizeReturnsOnCall[i] = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *FakeStorage) OpenBlob(arg1 string) (storage.StorageEntry, error) {
	fake.openBlobMutex.Lock()
	ret, specificReturn := fake.openBlobReturnsOnCall[len(fake.openBlobArgsForCall)]
	fake.openBlobArgsForCall = append(fake.openBlobArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.OpenBlobStub
	fakeReturns := fake.openBlobReturns
	fake.recordInvocation("OpenBlob", []interface{}{arg1})
	fake.openBlobMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStorage) OpenBlobCallCount() int {
	fake.openBlobMutex.RLock()
	defer fake.openBlobMutex.RUnlock()
	return len(fake.openBlobArgsForCall)
}

func (fake *FakeStorage) OpenBlobCalls(stub func(string) (storage.StorageEntry, error)) {
	fake.openBlobMutex.Lock()
	defer fake.openBlobMutex.Unlock()
	fake.OpenBlobStub = stub
}

func (fake *FakeStorage) OpenBlobArgsForCall(i int) string {
	fake.openBlobMutex.RLock()
	defer fake.openBlobMutex.RUnlock()
	argsForCall := fake.openBlobArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStorage) OpenBlobReturns(result1 storage.StorageEntry, result2 error) {
	fake.openBlobMutex.Lock()
	defer fake.openBlobMutex.Unlock()
	fake.OpenBlobStub = nil
	fake.openBlobReturns = struct {
		result1 storage.StorageEntry
		result2 error
	}{result1, result2}
}

func (fake *FakeStorage) OpenBlobReturnsOnCall(i int, result1 storage.StorageEntry, result2 error) {
	fake.openBlobMutex.Lock()
	defer fake.openBlobMutex.Unlock()
	fake.OpenBlobStub = nil
	if fake.openBlobReturnsOnCall == nil {
		fake.openBlobReturnsOnCall = make(map[int]struct {
			result1 storage.StorageEntry
			result2 error
		})
	}
	fake.openBlobReturnsOnCall[i] = struct {
		result1 storage.StorageEntry
		result2 error
	}{result1, result2}
}

func (fake *FakeStorage) OpenCommit(arg1 string) (*servercommit.Commit, error) {
	fake.openCommitMutex.Lock()
	ret, specificReturn := fake.openCommitReturnsOnCall[len(fake.openCommitArgsForCall)]
	fake.openCommitArgsForCall = append(fake.openCommitArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.OpenCommitStub
	fakeReturns := fake.openCommitReturns
	fake.recordInvocation("OpenCommit", []interface{}{arg1})
	fake.openCommitMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStorage) OpenCommitCallCount() int {
	fake.openCommitMutex.RLock()
	defer fake.openCommitMutex.RUnlock()
	return len(fake.openCommitArgsForCall)
}

func (fake *FakeStorage) OpenCommitCalls(stub func(string) (*servercommit.Commit, error)) {
	fake.openCommitMutex.Lock()
	defer fake.openCommitMutex.Unlock()
	fake.OpenCommitStub = stub
}

func (fake *FakeStorage) OpenCommitArgsForCall(i int) string {
	fake.openCommitMutex.RLock()
	defer fake.openCommitMutex.RUnlock()
	argsForCall := fake.openCommitArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStorage) OpenCommitReturns(result1 *servercommit.Commit, result2 error) {
	fake.openCommitMutex.Lock()
	defer fake.openCommitMutex.Unlock()
	fake.OpenCommitStub = nil
	fake.openCommitReturns = struct {
		result1 *servercommit.Commit
		result2 error
	}{result1, result2}
}

func (fake *FakeStorage) OpenCommitReturnsOnCall(i int, result1 *servercommit.Commit, result2 error) {
	fake.openCommitMutex.Lock()
	defer fake.openCommitMutex.Unlock()
	fake.OpenCommitStub = nil
	if fake.openCommitReturnsOnCall == nil {
		fake.openCommitReturnsOnCall = make(map[int]struct {
			result1 *servercommit.Commit
			result2 error
		})
	}
	fake.openCommitReturnsOnCall[i] = struct {
		result1 *servercommit.Commit
		result2 error
	}{result1, result2}
}

func (fake *FakeStorage) SaveBlob(arg1 string, arg2 netio.Communicator) error {
	fake.saveBlobMutex.Lock()
	ret, specificReturn := fake.saveBlobReturnsOnCall[len(fake.saveBlobArgsForCall)]
	fake.saveBlobArgsForCall = append(fake.saveBlobArgsForCall, struct {
		arg1 string
		arg2 netio.Communicator
	}{arg1, arg2})
	stub := fake.SaveBlobStub
	fakeReturns := fake.saveBlobReturns
	fake.recordInvocation("SaveBlob", []interface{}{arg1, arg2})
	fake.saveBlobMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStorage) SaveBlobCallCount() int {
	fake.saveBlobMutex.RLock()
	defer fake.saveBlobMutex.RUnlock()
	return len(fake.saveBlobArgsForCall)
}

func (fake *FakeStorage) SaveBlobCalls(stub func(string, netio.Communicator) error) {
	fake.saveBlobMutex.Lock()
	defer fake.saveBlobMutex.Unlock()
	fake.SaveBlobStub = stub
}

func (fake *FakeStorage) SaveBlobArgsForCall(i int) (string, netio.Communicator) {
	fake.saveBlobMutex.RLock()
	defer fake.saveBlobMutex.RUnlock()
	argsForCall := fake.saveBlobArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStorage) SaveBlobReturns(result1 error) {
	fake.saveBlobMutex.Lock()
	defer fake.saveBlobMutex.Unlock()
	fake.SaveBlobStub = nil
	fake.saveBlobReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStorage) SaveBlobReturnsOnCall(i int, result1 error) {
	fake.saveBlobMutex.Lock()
	defer fake.saveBlobMutex.Unlock()
	fake.SaveBlobStub = nil
	if fake.saveBlobReturnsOnCall == nil {
		fake.saveBlobReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveBlobReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStorage) SaveCommit(arg1 *servercommit.Commit) error {
	fake.saveCommitMutex.Lock()
	ret, specificReturn := fake.saveCommitReturnsOnCall[len(fake.saveCommitArgsForCall)]
	fake.saveCommitArgsForCall = append(fake.saveCommitArgsForCall, struct {
		arg1 *servercommit.Commit
	}{arg1})
	stub := fake.SaveCommitStub
	fakeReturns := fake.saveCommitReturns
	fake.recordInvocation("SaveCommit", []interface{}{arg1})
	fake.saveCommitMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStorage) SaveCommitCallCount() int {
	fake.saveCommitMutex.RLock()
	defer fake.saveCommitMutex.RUnlock()
	return len(fake.saveCommitArgsForCall)
}

func (fake *FakeStorage) SaveCommitCalls(stub func(*servercommit.Commit) error) {
	fake.saveCommitMutex.Lock()
	defer fake.saveCommitMutex.Unlock()
	fake.SaveCommitStub = stub
}

func (fake *FakeStorage) SaveCommitArgsForCall(i int) *servercommit.Commit {
	fake.saveCommitMutex.RLock()
	defer fake.saveCommitMutex.RUnlock()
	argsForCall := fake.saveCommitArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStorage) SaveCommitReturns(result1 error) {
	fake.saveCommitMutex.Lock()
	defer fake.saveCommitMutex.Unlock()
	fake.SaveCommitStub = nil
	fake.saveCommitReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStorage) SaveCommitReturnsOnCall(i int, result1 error) {
	fake.saveCommitMutex.Lock()
	defer fake.saveCommitMutex.Unlock()
	fake.SaveCommitStub = nil
	if fake.saveCommitReturnsOnCall == nil {
		fake.saveCommitReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveCommitReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStorage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.blobExistsMutex.RLock()
	defer fake.blobExistsMutex.RUnlock()
	fake.blobSizeMutex.RLock()
	defer fake.blobSizeMutex.RUnlock()
	fake.commitExistsMutex.RLock()
	defer fake.commitExistsMutex.RUnlock()
	fake.commitListMutex.RLock()
	defer fake.commitListMutex.RUnlock()
	fake.commitSizeMutex.RLock()
	defer fake.commitSizeMutex.RUnlock()
	fake.openBlobMutex.RLock()
	defer fake.openBlobMutex.RUnlock()
	fake.openCommitMutex.RLock()
	defer fake.openCommitMutex.RUnlock()
	fake.saveBlobMutex.RLock()
	defer fake.saveBlobMutex.RUnlock()
	fake.saveCommitMutex.RLock()
	defer fake.saveCommitMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStorage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ storage.Storage = new(FakeStorage)
